/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jaian;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.*;

public class AppTest {
    @Test
    public void answer() {
        assertThat(21 + 21, is(42));
    }
}
